// src/mockData.js
export const MOCK_PAPERS = [
    {
        "id": "0704.0001",
        "submitter": "Pavel Nadolsky",
        "authors": "C. Bal\\'azs, E. L. Berger, P. M. Nadolsky, C.-P. Yuan",
        "title": "Calculation of prompt diphoton production cross sections at Tevatron and LHC energies",
        "comments": "37 pages, 15 figures; published version",
        "journal-ref": "Phys.Rev.D76:013009,2007",
        "doi": "10.1103/PhysRevD.76.013009",
        "report-no": "ANL-HEP-PR-07-12",
        "categories": "hep-ph",
        "license": null,
        "abstract": "  A fully differential calculation in perturbative quantum chromodynamics is presented for the production of massive photon pairs at hadron colliders. All next-to-leading order perturbative contributions from quark-antiquark, gluon-(anti)quark, and gluon-gluon subprocesses are included...",
        "versions": [{"version": "v1", "created": "Mon, 2 Apr 2007 19:18:42 GMT"}],
        "update_date": "2008-11-26",
        "authors_parsed": [["Balázs", "C.", ""], ["Berger", "E. L.", ""], ["Nadolsky", "P. M.", ""]]
    },
    {
        "id": "2310.08560",
        "submitter": "Geoffrey Hinton",
        "authors": "Geoffrey Hinton",
        "title": "How to represent part-whole hierarchies in a neural network",
        "comments": "Accepted to GLOM 2023",
        "journal-ref": null,
        "doi": null,
        "report-no": null,
        "categories": "cs.CV cs.AI",
        "license": "http://arxiv.org/licenses/nonexclusive-distrib/1.0/",
        "abstract": "  This paper proposes a fictional method called GLOM for representing part-whole hierarchies in a neural network. It combines advances from transformers, neural fields, and contrastive representation learning to solve the binding problem...",
        "versions": [{"version": "v1", "created": "Tue, 10 Oct 2023 12:00:00 GMT"}],
        "update_date": "2023-10-10",
        "authors_parsed": [["Hinton", "Geoffrey", ""]]
    },
    {
        "id": "1706.03762",
        "submitter": "Ashish Vaswani",
        "authors": "Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Lukasz Kaiser, Illia Polosukhin",
        "title": "Attention Is All You Need",
        "comments": "31st Conference on Neural Information Processing Systems (NIPS 2017)",
        "journal-ref": null,
        "doi": null,
        "report-no": null,
        "categories": "cs.CL cs.LG",
        "license": "http://arxiv.org/licenses/nonexclusive-distrib/1.0/",
        "abstract": "  The dominant sequence transduction models are based on complex recurrent or convolutional neural networks in an encoder-decoder configuration. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms...",
        "versions": [{"version": "v1", "created": "Mon, 12 Jun 2017 17:00:00 GMT"}],
        "update_date": "2017-06-12",
        "authors_parsed": [["Vaswani", "Ashish", ""], ["Shazeer", "Noam", ""]]
    },
    {
        "id": "2401.12345",
        "submitter": "Demis Hassabis",
        "authors": "Google DeepMind Team",
        "title": "Gemini: A Family of Highly Capable Multimodal Models",
        "comments": "Technical Report",
        "journal-ref": null,
        "doi": null,
        "report-no": null,
        "categories": "cs.AI cs.CL",
        "license": "http://arxiv.org/licenses/nonexclusive-distrib/1.0/",
        "abstract": "  We introduce Gemini, a family of highly capable multimodal models. We show that Gemini Ultra typically outperforms state-of-the-art results on 30 of 32 widely-used academic benchmarks used in large language model (LLM) research and development...",
        "versions": [{"version": "v1", "created": "Wed, 10 Jan 2024 09:00:00 GMT"}],
        "update_date": "2024-01-10",
        "authors_parsed": [["Team", "Google DeepMind", ""]]
    },
    {
        "id": "2304.03456",
        "submitter": "Yann LeCun",
        "authors": "Yann LeCun",
        "title": "A Path Towards Autonomous Machine Intelligence",
        "comments": "Open Review Version",
        "journal-ref": null,
        "doi": null,
        "report-no": null,
        "categories": "cs.AI cs.RO",
        "license": "http://arxiv.org/licenses/nonexclusive-distrib/1.0/",
        "abstract": "  How could machines learn as efficiently as humans and animals? How could machines learn how the world works and acquire common sense? This paper proposes an architecture for autonomous intelligence consisting of six separate modules...",
        "versions": [{"version": "v1", "created": "Fri, 14 Apr 2023 14:00:00 GMT"}],
        "update_date": "2023-04-14",
        "authors_parsed": [["LeCun", "Yann", ""]]
    }
];
